version: '3.7'
services:

  server:
    build:
      context: ./server
    ports:
      - 4000:4000
    volumes:
      - /home/node/app/node_modules
      - ./server:/home/node/app:delegated
    environment:
      - PRISMA_DB_PROVIDER=postgresql
      - PRISMA_DB_URL=postgresql://prisma:prisma@postgres/
    command: 'yarn dev'